### PR TITLE
Issue 179 rework spatial data tables

### PR DESCRIPTION
**Pull request by rbroth**
Rename the subregion table to "aggregation_areas" - this should make it's purpose clearer.

Where appropriate, every area has an ISO code (3 letter) for the country it belongs to. I've divided the region into 3 types: country (just the country border), admin (admin regions such as counties and states, which add up to create country borders) and non-admin, which will be used for areas that are unrelated to administrative borders (e.g. soil types).

Other Repo:
- Improve readme, including steps to load GADM raw data 
- Import Malawi admin borders from Liberty
- Create Ethiopia Country and internal admin borders from GADM data

### CODE REVIEW

**Comment by andy-bevan** [comment]
The admin level columns are confusing me. How does that work then?

**Comment by rbroth** [comment]
> The admin level columns are confusing me. How does that work then?

I'm orienting myself with how GADM are doing it; see https://gadm.org/metadata.html for specification, and see gadm data for examples

name: leicestershire
country: GBR
admin_level: 2
admin0region:GBR -- ISO country code - probably redundant, but it's a work in progress)
admin1_region: GB-ENG -- some sort of ISO code for england
admin2_region: GB-LEC -- some sort of ISO code for leicestershire
admin3_region: NULL -- since this region is a admin level 2 region it doesn't  belong to a an admin level 3 region


I can see why it doesn't make sense, it's still very much a work in progress, and I'm not even sure if this is the best way to do it. I've mainly put in the merge request so that the new Malawi borders were in the system

**Review by andy-bevan — APPROVED** [review]
Ok I get the admin levels now.

**Comment by spenny-liam** [comment]
I'm having a quick look into it myself but if you could please try to clarify "some sort of ISO code". What code and standard exactly is expected for those columns to avoid later confusion?

**Comment by rbroth** [comment]
> 
> 
> I'm having a quick look into it myself but if you could please try to clarify "some sort of ISO code". What code and standard exactly is expected for those columns to avoid later confusion?

literally haven't decided yet. I think close the merge request since it's half-baked and only merge the data part

**Comment by rbroth** [comment]
@andy-bevan @spenny-liam related merge request: https://kwvmxgit.ad.nerc.ac.uk/bmgf-maps/data/db-test-data/-/merge_requests/18

**Review by spenny-liam — APPROVED** [review]

**Pull request merged**
