### PR TITLE
Biomarker table

### PR DESCRIPTION
**Pull request by rbroth**
- add in some script that refresh some materialized views. This is unrelated to biomarkers, but there's an abandoned pull request (gitlab: "merge request") that I want to close
- I'm renaming the `biomarker` table to `biomarker_measurements`. This is to make clear that this contains actual measurements that have been sampled from household_members, and to differentiate it from...
- The actual `Biomarker` table. This table contains a list of biomarkers, their user-friendly names, the units that they are measure in, and various other bits of metadata. This table is to serve as the canonical list of biomarkers, similar to how the `micronutrients` table serves as the canonical list of micronutrients. (#4)

Thus, there will be three biomarker-related tables:
- `biomarkers` listing them
- `biomarker_measurements`, with sampled values from HH members
- `biomarker_thresholds` (or similar name), which list these upper and lower values (in the nits as specified in the biomarker table) that should be found in the samples of various groups.

@andy-bevan, does the above make sense?

### CODE REVIEW

**Comment by andy-bevan** [comment]
Yes makes sense. 
Are you naming tables as plural or singular?
So the biomarker_threshold table will have the biomarker_id from biomarker table as FK?

**Comment by rbroth** [comment]
> Are you naming tables as plural or singular?

Erk, I've just realized I've mixed and matched. I guess it should be singular, really. I'll make the change to this table, and open an issue

> So the biomarker_threshold table will have the biomarker_id from biomarker table as FK?

That makes sense to me

**Comment by andy-bevan** [comment]
I am wondering if we should consider normalising the biomarker_measurement table so that we have a single biomarker column rather than a column for each biomarker value?

**Comment by rbroth** [comment]
> I am wondering if we should consider normalising the biomarker_measurement table so that we have a single biomarker column rather than a column for each biomarker value?

A sort of [EAV pattern](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model)? 
I considered that back when I was creating the fooditem table, which also has lots of columns and measurements, but ultimately decided against it, since it would add more complexity with regards to storing units and similar columns and other metadata. ([Possibly related discussion in the old (abandoned)  BGS gitlab repo](https://kwvmxgit.ad.nerc.ac.uk/bmgf-maps/bmgf-maps/-/issues/2)). It seems to be working reasonably well so far, so I greatly prefer to use the same sort of patterns with the biomarker stuff unless there are very compelling reasons.

**Comment by andy-bevan** [comment]
More generic question: are you keeping a separate ER diagram updated or just using the DBeaver autogenerated one or something else?

**Comment by rbroth** [comment]
> More generic question: are you keeping a separate ER diagram updated or just using the DBeaver autogenerated one or something else?

I haven't been keeping any ER diagram, I've just been using DBeaver (and keeping everything in my head)

**Comment by rbroth** [comment]
@spenny-liam if you could have a look and hit the approve button, I think Andy mentioned that he's waiting on it to be merged

**Review by andy-bevan — APPROVED** [review]

**Review by spenny-liam — APPROVED** [review]

**Pull request merged**
