### PR TITLE
fix: add ordering to other intervention json views:

### PR DESCRIPTION
**Pull request by bgsandan**
### General Checklist
- [ ] Database objects and columns have comments (or not applicable)
- [ ] The project README.md has been updated to reflect any changes (or not applicable)

### CODE REVIEW

**Comment by bgsandan** [comment]
Closes #333

**Comment by rbroth** [comment]
Have you tested this with the API?

**Comment by bgsandan** [comment]
> Have you tested this with the API?

Yup. It seems to behave. The main change is just that there were two views that needed an `order by`, you had found one but not the other :). I added a `ASC` to yours too which I know isn't strictly necessary but I prefer for clarity when quickly previewing code

**Comment by rbroth** [comment]
Cool, in that case feel free to merge :)

**Pull request merged**
